# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [30]:
import numpy as np

## Vector operations

In [31]:
u = np.array([2, 4, 5, 6]) 
#an array - whole row vector 
#use transpose function to convert row vector to column vector
u

array([2, 4, 5, 6])

In [32]:
2 * u # Scalar multiplication: Multiply by number (2 * v)

array([ 4,  8, 10, 12])

In [33]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [34]:
u + v

array([3, 4, 5, 8])

In [35]:
u * v #dot product: vector * vector = element-wise multiplications


array([ 2,  0,  0, 12])

## Multiplication

In [36]:
v.shape #shape of vector (4, 0) - 4 rows, 0 columns

(4,)

In [55]:
v.shape[0] #first element - number of rows

4

In [56]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] 
    #must be same length (same number of elements] - otherwise cannot multiply
    n = u.shape[0]
    result = 0.0   #result variable to store sum of multiplications - 0.0 to make it float
    for i in range(n): #go over all elements in array u for each index i
        result += u[i] * v[i] #multiply corresponding elements and add to result - i is index
    return result
    

In [57]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [40]:
u.dot(v) #numpy dot product function

np.int64(14)

In [51]:
np.dot(u, v) #numpy dot product function alternative
#or u.dot(v)

np.int64(14)

In [81]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [43]:
U.shape

(3, 4)

In [44]:
#matrix-vector multiplication
#matrix U (3x4) multiplied by vector v (4x1) = result vector (3x1)
#each row of u multiplied by vector v
v

array([1, 0, 0, 2])

In [45]:
v.shape

(4,)

In [ ]:
def matrix_vector_multiplication(U, v):  #matrices transform vectors (linear regression: X * weights = predictions)
    #builds on dot product
    assert U.shape[1] == v.shape[0] #Columns in U = Rows (length) in v

    num_rows = U.shape[0] #retrieve number of rows in U - number of elements in result vector

    result = np.zeros(num_rows) #initialize result vector with zeros
    
    for i in range(num_rows):
        result[i]= vector_vector_multiplication(U[i], v) #multiply each row of U with vector v and store in result vector

    return result

In [47]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [48]:
U.dot(v)

array([14,  5,  5])

In [78]:
U@v # @ operator for matrix multiplication

array([14,  5,  5])

In [54]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [72]:
def matrix_matrix_multiplication(U, V): #full transformations (neural net layers: weights *inputs)
    #loops over columns (in V)
    assert U.shape[1] == V.shape[0] #Columns in U = Rows in V

    num_rows = U.shape[0] 
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols)) #initialize result matrix with zeros - based on number of rows in U and number of columns in V

    for i in range(num_cols):
        vi = V[:, i] #Extract column i of matrix V
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi #Fill column i of result matrix
    
    return result


In [73]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [74]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [77]:
U @ V # @ operator for matrix multiplication

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [ ]:
#matrix with diagonal contains 1, other elements are 0
#"I" does nothing when multiplied (like 1 in scalars). 
# Essential for solving systems.
#1*x = x
#x*1 = x
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [88]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
V @ I # Cannot be I @ V because columns in I = rows in V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [93]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
V[[0, 1, 2]] #Select rows 0, 1, 2 from matrix V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [95]:
Vsq = V[[0, 1, 2]]
Vsq

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [97]:
#"Solves" Ax = b (e.g., find weights in regression). Only for square, invertible matrices.
inv = np.linalg.inv(Vsq)
inv


array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [100]:
#test: inverse * original = identity matrix
Vsq @ inv
#or Vsq.dot(inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas